**Aluno(a): João Victor Soares de Almeida**

<h5> Exercício I </h5>

In [1]:
import numpy as np
import scipy.linalg as sla

In [3]:

def elimin_gaussiana(a, b,imp=False, norma='inf'):
    # matriz estendida Me
    b = np.mat(b).T
    Me = np.concatenate((a, b), axis=1)
    if imp: print('Matriz estendida: \n', Me, '\n\n')
    if imp: print('=' * 80)
    for j in range(Me.shape[-1] - 2):  # coluna
        if imp: print('Operação na coluna', j)
        if imp: print('=' * 80, '\n\n')
        for i in range(j + 1, Me.shape[0]):  # linha
            Me[i] = Me[i] - (Me[i, j] / Me[j, j]) * Me[j]  # operações com cada linha
            if imp: print('Operação na linha', i, ':', Me[i], '\n')
            if imp: print('Matriz escalonando: \n', Me, '\n')
        if imp: print('=' * 80)
    if imp: print('\nMatriz escalonada: \n', Me, '\n')
    Matriz_A = np.delete(Me, -1, axis=1)  # matriz de coeficientes escalonada
    Vetor_b = Me[:, -1]  # matriz de termos independentes escalonada
    Vetor_x = sla.solve_triangular(Matriz_A, Vetor_b)  # solução do sistema escalonado
    if imp: print('=' * 80, '\n\nSolução do sistema: \n', Vetor_x)
    # verificação do erro do sistema
    if norma is 'inf': norma = np.inf
    if norma is '-inf': norma = -np.inf
    Erro = sla.norm(b - a.dot(Vetor_x), ord=norma)
    return (Matriz_A, Vetor_b, Vetor_x, Erro)


**Exemplo 1**

In [6]:
a = np.array([[2, 3, -1], [4, 4, -3], [2, -3, 1]])
b = np.array([5, 3, -1])
M = elimin_gaussiana(a, b)
print('Array Solução:\n',M[2])

Array Solução:
 [[1.]
 [2.]
 [3.]]


In [7]:
sla.solve(a,b)

array([1., 2., 3.])

**Exemplo 2**

In [ ]:
a = np.array([[1, 1, 1], [4, 4, 2], [2, 1, -1]])
b = np.array([1, 2, 0])
elimin_gaussiana(a, b)

**Alteração da função para que o erro não ocorra**

In [9]:
def gausElimin(a, b, piv = True, imp=False, norma='inf'):
    # matriz estendida Me
    b = np.mat(b).T
    Me = np.array(np.concatenate((a, b), axis=1))
    tamanhoMat = len(Me)
    if imp: print('Matriz estendida: \n', Me, '\n\n')
    if imp: print('=' * 80)
        
        
    for i in range(tamanhoMat - 1):
        if piv:
            maiorIndice = abs(Me[i:, i]).argmax() + i
            if Me[maiorIndice, i] == 0:
                raise ValueError('Matriz Singular')
            if maiorIndice != i:
                Me[[i, maiorIndice]] = Me[[maiorIndice, i]]
                if imp: print("Troca entre as linhas %i e %i", k, maiorIndice)
                if imp: print('Matriz escalonando: \n',Me,'\n')
        else:
            if Me[i,i] == 0:
                raise ValueError('Pivô é zero')
        
        for prox in range(i +1, tamanhoMat):
            temp = Me[prox, i]/Me[i,i]
            Me[prox, i:] = Me[prox, i:] - temp* Me[i,i:]
            if imp: print('Operação na linha %i: %i',prox, Me[prox])
            if imp: print('Matriz escalonando: \n',Me,'\n')
            
    if imp: print('\nMatriz escalonada: \n', Me, '\n')
    Matriz_A = np.delete(Me, -1, axis=1)  # matriz de coeficientes escalonada
    Vetor_b = Me[:, -1]  # matriz de termos independentes escalonada
    Vetor_x = sla.solve_triangular(Matriz_A, Vetor_b)  # solução do sistema escalonado
    if imp: print('=' * 80, '\n\nSolução do sistema: \n', Vetor_x)
    # verificação do erro do sistema
    if norma is 'inf': norma = np.inf
    if norma is '-inf': norma = -np.inf
    Erro = sla.norm(b - a.dot(Vetor_x), ord=norma)
    return (Matriz_A, Vetor_b, Vetor_x, Erro)

In [10]:
a = np.array([[1, 1, 1], [4, 4, 2], [2, 1, -1]]).astype(float)
b = np.array([1, 2, 0]).astype(float)

print('Array Solução:',gausElimin(a, b)[2])

Array Solução: [ 1. -1.  1.]


**Exercício II**

In [11]:
solucaoUm = np.array([1,1,1])
solucaoDois = np.array([4.5,0,1.01])

ErroAb = solucaoUm - solucaoDois
ErroRe = ErroAb/solucaoDois


print('Erro Absoluto:',ErroAb, '\nErroRelativo:', ErroRe)

Erro Absoluto: [-3.5   1.   -0.01] 
ErroRelativo: [-0.77777778         inf -0.00990099]


C:\Users\joaos\Anaconda1\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


**Exercício III**

In [12]:
def gausElimin(a, b, piv = True, imp=False, norma='inf'):
    # matriz estendida Me
    b = np.mat(b).T
    Me = np.array(np.concatenate((a, b), axis=1))
    tamanhoMat = len(Me)
    if imp: print('Matriz estendida: \n', Me, '\n\n')
    if imp: print('=' * 80)
        
        
    for i in range(tamanhoMat - 1):
        if piv:
            maiorIndice = abs(Me[i:, i]).argmax() + i
            if Me[maiorIndice, i] == 0:
                raise ValueError('Matriz Singular')
            if maiorIndice != i:
                Me[[i, maiorIndice]] = Me[[maiorIndice, i]]
                if imp: print("Troca entre as linhas %i e %i", k, maiorIndice)
                if imp: print('Matriz escalonando: \n',Me,'\n')
        else:
            if Me[i,i] == 0:
                raise ValueError('Pivô é zero')
        
        for prox in range(i +1, tamanhoMat):
            temp = Me[prox, i]/Me[i,i]
            Me[prox, i:] = Me[prox, i:] - temp* Me[i,i:]
            if imp: print('Operação na linha %i: %i',prox, Me[prox])
            if imp: print('Matriz escalonando: \n',Me,'\n')
            
    if imp: print('\nMatriz escalonada: \n', Me, '\n')
    Matriz_A = np.delete(Me, -1, axis=1)  # matriz de coeficientes escalonada
    Vetor_b = Me[:, -1]  # matriz de termos independentes escalonada
    Vetor_x = sla.solve_triangular(Matriz_A, Vetor_b)  # solução do sistema escalonado
    if imp: print('=' * 80, '\n\nSolução do sistema: \n', Vetor_x)
    # verificação do erro do sistema
    if norma is 'inf': norma = np.inf
    if norma is '-inf': norma = -np.inf
    Erro = sla.norm(b - a.dot(Vetor_x), ord=norma)
    return (Matriz_A, Vetor_b, Vetor_x, Erro)

In [13]:
c = np.array([[1,4,52],[27,110,-3],[22,2,14]]).astype(float)
d = np.array([57,134,38]).astype(float)

print('Array Solução:',gausElimin(c,d)[2])

Array Solução: [1. 1. 1.]


**Exercício IV**

In [7]:
def gausElimin(a, b, piv = True, imp=False, norma='inf'):
    # matriz estendida Me
    b = np.mat(b).T
    Me = np.array(np.concatenate((a, b), axis=1))
    tamanhoMat = len(Me)
    if imp: print('Matriz estendida: \n', Me, '\n\n')
    if imp: print('=' * 80)
           
    for i in range(tamanhoMat - 1):
        if piv:
            maiorIndice = abs(Me[i:, i]).argmax() + i
            if Me[maiorIndice, i] == 0:
                raise ValueError('Matriz Singular')
            if maiorIndice != i:
                Me[[i, maiorIndice]] = Me[[maiorIndice, i]]
                if imp: print("Troca entre as linhas %i e %i", k, maiorIndice)
                if imp: print('Matriz escalonando: \n',Me,'\n')
        else:
            if Me[i,i] == 0:
                raise ValueError('Pivô é zero')
        
        for prox in range(i +1, tamanhoMat):
            temp = Me[prox, i]/Me[i,i]
            Me[prox, i:] = Me[prox, i:] - temp* Me[i,i:]
            if imp: print('Operação na linha %i: %i',prox, Me[prox])
            if imp: print('Matriz escalonando: \n',Me,'\n')
            
    if imp: print('\nMatriz escalonada: \n', Me, '\n')
    Matriz_A = np.delete(Me, -1, axis=1)  # matriz de coeficientes escalonada
    Vetor_b = Me[:, -1]  # matriz de termos independentes escalonada
    Vetor_x = sla.solve_triangular(Matriz_A, Vetor_b)  # solução do sistema escalonado
    if imp: print('=' * 80, '\n\nSolução do sistema: \n', Vetor_x)
    # verificação do erro do sistema
    if norma is 'inf': norma = np.inf
    if norma is '-inf': norma = -np.inf
    Erro = sla.norm(b - a.dot(Vetor_x), ord=norma)
    return (Matriz_A, Vetor_b, Vetor_x, Erro)

In [12]:
solucaoUm = np.array([1,0,3, -5])
solucaoDois = np.array([1,0,0,4])

ErroAb = solucaoUm - solucaoDois
ErroRe = ErroAb/solucaoDois

print('Erro Absoluto:',ErroAb, '\nErroRelativo:', ErroRe)

Erro Absoluto: [ 0  0  3 -9] 
ErroRelativo: [ 0.     nan   inf -2.25]


C:\Users\joaos\Anaconda1\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """
C:\Users\joaos\Anaconda1\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


**Exercício V**

**Exercício VI**

In [13]:
A = np.array([[1,1,1],[2,1,-1],[2,-1,1]])
B = np.array([-2,1,3])
A

array([[ 1,  1,  1],
       [ 2,  1, -1],
       [ 2, -1,  1]])

In [24]:
(P,L,U)= sla.lu(A.T)

print(P.T)

print(L.T)

print(U.T)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1.         1.         1.        ]
 [0.         1.         0.33333333]
 [0.         0.         1.        ]]
[[ 1.          0.          0.        ]
 [ 2.         -3.          0.        ]
 [ 2.         -1.         -2.66666667]]


In [19]:
lu,piv = sla.lu_factor(A)
print(lu)

print(piv)

[[ 2.    1.   -1.  ]
 [ 1.   -2.    2.  ]
 [ 0.5  -0.25  2.  ]]
[1 2 2]


In [20]:
sla.lu_solve((lu, piv), B)

array([ 1., -2., -1.])

**LU**: 
- Faz a decomposição LU de uma matriz , decompondo no formato . Nessa função, a implementação é feita usando **somente** o scipy. Se permute_l = False, retorna P, L, U, caso permute_l = True, retorna PL e a matriz U

**A=PLU**
- **lu_factor**:Faz a decomposição LU de uma matriz , decompondo no formato . Porém, essa função, implementa o método *GETRF da LAPACK. 


Por fim, chegamos a conclusão que apesar de os métodos utilizam de estratégias diferentes para resolver o cálculo da Matriz, porém ambos chegam ao mesmo resultado.