In [2]:
import numpy as np
import scipy.linalg as sla

**Exercício - 9.4**

In [2]:
matrizA = [[0,2,5],[2,1,1],[3,1,0]]
matrizB = [1,1,2]

In [ ]:
def GausPivot(A,b):
    n = len(A)
    M = A

    i = 0
    for x in M:
     
        x.append(b[i])
        i += 1

    for k in range(n):
        for i in range(k,n):
            
            if abs(M[i][k]) > abs(M[k][k]):
                M[k], M[i] = M[i],M[k]
            else:
                pass

        for j in range(k+1,n):
            q = float(M[j][k]) / M[k][k]
            for m in range(k, n+1):
                  M[j][m] -=  q * M[k][m]

    x = [0 for i in range(n)]

    x[n-1] =float(M[n-1][n])/M[n-1][n-1]
    for i in range (n-1,-1,-1):
        z = 0
        for j in range(i+1,n):
            z = z  + float(M[i][j])*x[j]
            x[i] = float(M[i][n] - z)/M[i][i]
            
    
    return x
GausPivot(A,b)


**9.6**

In [3]:
def matIngenua(A,b):
    m = len(A)
    n = len(A[0])
    b = np.reshape(b, (-1, 1))
    matAum = np.concatenate((A, b), axis=1)
    
    if m != n:
        print("Error")
    nb = n + 1
        
    for k in range(1, n-1):
        for i in range(k+1, n):
            fator = matAum[i][k]/ matAum[k][k]
            matAum[i][k:nb] = matAum[i][k:nb] - fator *matAum[k][k:nb]
            
    x = np.zeros((n,1))
    x[n-1] = matAum[n-1,nb-1]/matAum[n-1][n-1]
    
    for i in range(n-1, -1, 1):
        x[i] = (matAum[i][nb] - (matAum[i][i+1:n] * x[i+1:n]))/matAum[i][i]
    
    return x

matIngenua(matrizA,matrizB)
    

array([[ 0.],
       [ 0.],
       [-1.]])

**Exercício - 9.7**

In [ ]:
A = [[2, -6, -1], [-3,-1,7], [-8,1,-2]]
print(len(A))
b = [-38,-34,-20]    

def Gauss(A,b):
    n = len(A)
    M = A

    i = 0
    for x in M:
     
        x.append(b[i])
        i += 1

    for k in range(n):
        for i in range(k,n):
            
            if abs(M[i][k]) > abs(M[k][k]):
                M[k], M[i] = M[i],M[k]
            else:
                pass

        for j in range(k+1,n):
            q = float(M[j][k]) / M[k][k]
            for m in range(k, n+1):
                  M[j][m] -=  q * M[k][m]

    x = [0 for i in range(n)]

    x[n-1] =float(M[n-1][n])/M[n-1][n-1]
    for i in range (n-1,-1,-1):
        z = 0
        for j in range(i+1,n):
            z = z  + float(M[i][j])*x[j]
            x[i] = float(M[i][n] - z)/M[i][i]
            
    
    return x
Gauss(A,b)

**Exercício 9.9**

In [3]:
A = np.array([[120, -30, 0, 200],  
              [90, -90, 0, 0],  
              [40, 60, -120, -500]], dtype='int') 
print(A)  
print('\n')


aux = np.copy(A[1,:])  
A[1,:] = np.copy(A[0,:])  
A[0,:] = np.copy(aux)  
print(A)  
print('\n') 

 
A[1,:] = A[1,:] - (A[1,0]/A[0,0])*A[0,:]  
A[2,:] = A[2,:] - (A[2,0]/A[0,0])*A[0,:]  
print(A)  
print('\n') 


A[2,:] = A[2,:] - (A[2,1]/A[1,1])*A[1,:]  
print(A)  
print('\n') 


x = np.zeros(3)  
x[2] = A[2,3]/A[2,2];  
x[1] = (A[1,3] - A[1,2]*x[2])/A[1,1];  
x[0] = (A[0,3] - A[0,2]*x[2] - A[0,1]*x[1])/A[0,0]  
print("C1 : ",x[0])
print('\n')
print("C2 : ",x[1])
print('\n')
print("C3 : ",x[2])

[[ 120  -30    0  200]
 [  90  -90    0    0]
 [  40   60 -120 -500]]


[[  90  -90    0    0]
 [ 120  -30    0  200]
 [  40   60 -120 -500]]


[[  90  -90    0    0]
 [   0   90    0  200]
 [   0  100 -120 -500]]


[[  90  -90    0    0]
 [   0   90    0  200]
 [   0    0 -120 -722]]


C1 :  2.2222222222222223


C2 :  2.2222222222222223


C3 :  6.016666666666667


**Exercício 10.3**

In [5]:
def  trocaLinha(A,i,j):
    buffer = A[i]
    A[i] = A[j]
    A[j] = buffer
    return A

def multLinha(A,i,alfa):
    A[i] = alfa*A[i]
    return A

def subsLinha(A,i,k,alfa):
    A[i] = A[i] + alfa*A[k]
    return A

# step k of gauss elimination:
def Gauss(A,k):
    L=range(len(A))
    for j in L[k+1:]:
        m=-A[j,k]/A[k,k]
        A=subsLinha(A,j,k,m)
    return A


def formaTriangular(A):
    L=len(A)
    for k in range(L):
        if A[k,k] != 0:
            A=Gauss(A,k)
            print (A) 
            print('\n')
        else: 
            print (' falhou no passo ', k)
    return A

A = np.array([[7, 2, -3, -12],
         [2, 5, -3, -20],
         [1, -1, -6, -26]], dtype = 'int')
B=formaTriangular(A)
x = np.zeros(3)  
x[2] = A[2,3]/A[2,2];  
x[1] = (A[1,3] - A[1,2]*x[2])/A[1,1];  
x[0] = (A[0,3] - A[0,2]*x[2] - A[0,1]*x[1])/A[0,0] 
print("X1: ", x[0])
print('\n')
print("X2: ", x[1])
print('\n')
print("X3: ", x[2])
print('\n')

[[  7   2  -3 -12]
 [  0   4  -2 -16]
 [  0  -1  -5 -24]]


[[  7   2  -3 -12]
 [  0   4  -2 -16]
 [  0   0  -5 -28]]


[[  7   2  -3 -12]
 [  0   4  -2 -16]
 [  0   0  -5 -28]]


X1:  1.0285714285714282


X2:  -1.2000000000000002


X3:  5.6




**Exercício 10.4**

In [7]:
def fatoraLU(A):  
    U = np.copy(A)  
    n = np.shape(U)[0]  
    L = np.eye(n)  
    for j in np.arange(n-1):  
        for i in np.arange(j+1,n):  
            L[i,j] = U[i,j]/U[j,j]  
            for k in np.arange(j+1,n):  
                U[i,k] = U[i,k] - L[i,j]*U[j,k]  
            U[i,j] = 0  
    return L, U
fatoraLU(A)

(array([[ 1.        ,  0.        ,  0.        ],
        [ 0.28571429,  1.        ,  0.        ],
        [ 0.14285714, -0.29032258,  1.        ]]),
 array([[  7.        ,   2.        ,  -3.        , -12.        ],
        [  0.        ,   4.42857143,  -2.14285714, -20.        ],
        [  0.        ,   0.        ,  -6.19354839, -26.        ]]))

In [9]:
P,L,U = sla.lu(A)
print(P)
print(L)
print(U)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.          0.          0.        ]
 [ 0.28571429  1.          0.        ]
 [ 0.14285714 -0.29032258  1.        ]]
[[  7.           2.          -3.         -12.        ]
 [  0.           4.42857143  -2.14285714 -16.57142857]
 [  0.           0.          -6.19354839 -29.09677419]]


**Exercício 10.5**

In [10]:
def fatoraLU(A):  
    U = np.copy(A)  
    n = np.shape(U)[0]  
    L = np.eye(n)  
    for j in np.arange(n-1):  
        for i in np.arange(j+1,n):  
            L[i,j] = U[i,j]/U[j,j]  
            for k in np.arange(j+1,n):  
                U[i,k] = U[i,k] - L[i,j]*U[j,k]  
            U[i,j] = 0  
    print(L)
    print('\n')
    print(U)

In [11]:
A = np.array([[2, -6, -1, -38],
         [-3, -1, 6, -34],
         [-8, 1, -2, -40]], dtype = 'double')
fatoraLU(A)

[[ 1.   0.   0. ]
 [-1.5  1.   0. ]
 [-4.   2.3  1. ]]


[[  2.    -6.    -1.   -38.  ]
 [  0.   -10.     4.5  -34.  ]
 [  0.     0.   -16.35 -40.  ]]


In [12]:
A = np.array([[2, -6, -1, -38],
         [-3, -1, 6, -34],
         [-8, 1, -2, -40]], dtype = 'double')
P,L,U=sla.lu(A)
print(P)
print('\n')
print(L)
print('\n')
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


[[ 1.          0.          0.        ]
 [-0.25        1.          0.        ]
 [ 0.375       0.23913043  1.        ]]


[[ -8.           1.          -2.         -40.        ]
 [  0.          -5.75        -1.5        -48.        ]
 [  0.           0.           7.10869565  -7.52173913]]


**Exercício 10.10**

In [13]:
def fatoraLU(A):  
    U = np.copy(A)  
    n = np.shape(U)[0]  
    L = np.eye(n)  
    for j in np.arange(n-1):  
        for i in np.arange(j+1,n):  
            L[i,j] = U[i,j]/U[j,j]  
            for k in np.arange(j+1,n):  
                U[i,k] = U[i,k] - L[i,j]*U[j,k]  
            U[i,j] = 0  
    print(L)
    print('\n')
    print(U)

In [14]:
A = np.array([[3, -2, 1, -10],
         [2, 6, -4, 44],
         [-8, -2, 5, -26]], dtype = 'double')
fatoraLU(A)

[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [-2.66666667 -1.          1.        ]]


[[  3.          -2.           1.         -10.        ]
 [  0.           7.33333333  -4.66666667  44.        ]
 [  0.           0.           3.         -26.        ]]


In [15]:
A = np.array([[3, -2, 1, -10],
         [2, 6, -4, 44],
         [-8, -2, 5, -26]], dtype = 'double')
P,L,U=sla.lu(A)
print(P)
print('\n')
print(L)
print('\n')
print(U)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


[[ 1.     0.     0.   ]
 [-0.25   1.     0.   ]
 [-0.375 -0.5    1.   ]]


[[ -8.    -2.     5.   -26.  ]
 [  0.     5.5   -2.75  37.5 ]
 [  0.     0.     1.5   -1.  ]]


In [28]:
import swap     
import error

def LUdecomp(a,tol=1.0e-9): 
    n = len(a) 
    seq = np.array(range(n))
# Set up scale factors 
    s = np.zeros((n)) 
    
    for i in range(n): 
        s[i] = max(abs(a[i,:]))
        
    for k in range(0,n-1):
    # Row interchange, if needed 
        p = np.argmax(np.abs(a[k:n,k])/s[k:n]) + k 
        if abs(a[p,k]) < tol: error.err("Matrix is singular") 
        if p != k: 
            swap.swapRows(s,k,p) 
            swap.swapRows(a,k,p) 
            swap.swapRows(seq,k,p)

    for i in range(k+1,n): 
        if a[i,k] != 0.0: 
            lam = a[i,k]/a[k,k]
            a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n] 
            a[i,k] = lam 
            return a,seq
            
def LUsolve(a,b,seq): 
    n = len(a)
    
    x = b.copy()
    for i in range(n):
        x[i] = b[seq[i]]
        
    for k in range(1, n):
        x[k] = x[k] - np.dot(a[k,0:k], x[0:k])
    x[n-1] = x[n-1]/a[n-1,n-1]
    for k in range(n-2, -1, -1):
        x[k] = (x[k] - np.dot(a[k,k+1:n], x[k+1:n]))/a[k,k]
    return x

In [40]:
a = np.array([[2,-2,6],[-2,4,3],[-1,8,4]])
b = np.array([16,0,-1])

In [41]:
LUdecomp(a)

AttributeError: module 'swap' has no attribute 'swapRows'